---
# tasks file for nginx-lb

- name: Install EPEL Repo
  yum: name={{ epel_rpm }} state=installed
  tags: lb
  when: configure_lb

- name: Start and enable NTP
  service: name=ntpd  state=started  enabled=yes
  tags: lb
  when: configure_lb

- name: Install nginx
  yum: name=nginx state=installed
  tags: lb
  when: configure_lb

- name: Start & Enable nginx
  service: name=nginx state=started enabled=yes
  tags: lb
  when: configure_lb

- name: Add nginx lb config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  when: inventory_hostname == 'lb'
  notify: Restart nginx
  tags: lb
  when: configure_lb
