- name: Manage Cluster Settings (secure)
  cockroach_cluster_settings:
        name={{ item.name }}
        value={{ item.value }}
        path={{ install_location }}
        host={{ inventory_hostname }}
        certs_dir={{ certs_dir |default (omit)}}
        state=present
  with_items:
        - "{{ cluster_settings }}"
  when: inventory_hostname == cluster_master and cluster_settings is defined
  tags: cluster_settings
  become_user: "{{ cockroach_user }}"
