- hosts: "{{ hostgroup }}"
  become: true
  roles:
     - common
     - node-exporter
     - {role: haproxy-exporter, when: loadbalancer_node and lb_type |lower == 'haproxy'}
     - {role: prometheus, when: prometheus_node}
     - {role: grafana, when: grafana_node}
