---

- name: lb
  group: "[lb]"
  box: oravirt/ol73
  ram: 1024
  cpu: 1
  ip: 192.168.9.40
  os_extra_disk: "no"
  db_extra_disk: "no"
  #private_key: /home/vagrant/insecure_private_key
  private_key: /home/miksan/.vagrant.d/insecure_private_key

- name: cr1
  group: "[cockroach]"
  box: oravirt/ol73
  ram: 1024
  cpu: 1
  ip: 192.168.9.41
  os_extra_disk: "no"
  os_extra_disk_size: 50
  os_num_extra_disk: 1
  db_extra_disk: "no"
  db_extra_disk_size: 10
  db_num_extra_disk: 3
  #private_key: /home/vagrant/insecure_private_key
  private_key: /home/miksan/.vagrant.d/insecure_private_key

- name: cr2
  group: "[cockroach]"
  box: oravirt/ol73
  ram: 1024
  cpu: 1
  ip: 192.168.9.42
  os_extra_disk: "no"
  os_extra_disk_size: 50
  os_num_extra_disk: 1
  db_extra_disk: "no"
  db_extra_disk_size: 10
  db_num_extra_disk: 3
  #private_key: /home/vagrant/insecure_private_key
  private_key: /home/miksan/.vagrant.d/insecure_private_key

- name: cr3
  group: "[cockroach]"
  box: oravirt/ol73
  ram: 1024
  cpu: 1
  ip: 192.168.9.43
  os_extra_disk: "no"
  os_extra_disk_size: 50
  db_extra_disk: "no"
  db_extra_disk_size: 10
  db_num_extra_disk: 3
  #private_key: /home/vagrant/insecure_private_key
  private_key: /home/miksan/.vagrant.d/insecure_private_key
