- name: Install nginx
  yum: name=nginx state=installed
  tags: lb
  when: configure_lb

- name: Start & Enable nginx
  service: name=nginx state=started enabled=yes
  tags: lb
  when: configure_lb

- name: Add nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: Restart nginx
  tags: lb
  when: configure_lb
