- basename_vm: crdb-dc1-
  num_vm: 3
  hostgroup: crdb-dc1
  domain: internal.lab
  box: oravirt/centos73
  vagrant_user: vagrant
  vagrant_pass: vagrant
  ram: 1024
  cpu: 1
  base_pub_ip: 192.168.9.200
  port_forward: True
  forwarded_port:
          - {hostport: 36257, guestport: 26257}
  base_disk_path:
  create_local_disk: False
  local_disks:
     - {name: crdb, size: 75, count: 1}
  create_shared_disk: false
  provisioning:
  provisioning_env_override: false

- basename_vm: lb
  num_vm: 1
  hostgroup: lb
  domain: internal.lab
  box: oravirt/centos73
  vagrant_user: vagrant
  vagrant_pass: vagrant
  vagrant_private_key:
  ram: 1024
  cpu: 1
  base_pub_ip: 192.168.10.200
  port_forward: True
  forwarded_port:
          - {hostport: 26257, guestport: 26257}
          - {hostport: 8080, guestport: 8080}

- basename_vm: graph
  num_vm: 1
  hostgroup: graph
  domain: internal.lab
  box: oravirt/centos73
  vagrant_user: vagrant
  vagrant_pass: vagrant
  vagrant_private_key:
  ram: 1024
  cpu: 1
  base_pub_ip: 192.168.10.100
  port_forward: True
  forwarded_port:
          - {hostport: 3000, guestport: 3000}
