---
# tasks file for cockroach-db
- name: Create databases
  cockroach_db: name={{ item }} path={{ install_location }}/{{ install_version }} host={{ inventory_hostname }} state=present
  with_items:
        - "{{ databases }}"
  when: inventory_hostname == cluster_master and databases is defined
  tags: create_db
