- name: Create databases (secure)
  cockroach_db:
        name={{ item }}
        path={{ install_location }}
        host={{ inventory_hostname }}
        certs_dir={{ certs_dir |default (omit)}}
        state=present
  with_items:
        - "{{ databases }}"
  when: inventory_hostname == cluster_master and databases is defined
  tags: create_db
  become_user: "{{ cockroach_user }}"
