
- name: Start master node (insecure)
  cockroach_cluster:
           path={{ install_location }}
           host={{ ansible_hostname }}
           store={{ datastore |default (omit)}}
           cache={{ cache |default (omit)}}
           log_dir={{ log_dir | default(omit) }}
           locality={{ locality | default(omit) }}
           state=started
  when: inventory_hostname == cluster_master
  tags: start_cluster,restart_cluster,master
  become_user: "{{ cockroach_user }}"

- name: Start other nodes (insecure)
  cockroach_cluster:
           path={{ install_location }}
           host={{ ansible_hostname }}
           store={{ datastore |default (omit)}}
           join=True
           cluster_master={{ cluster_master }}
           cache={{ caches |default (omit)}}
           log_dir={{ log_dir | default(omit) }}
           locality={{ locality | default(omit) }}
           state=started
  when: inventory_hostname != cluster_master
  tags: join_cluster,start_cluster,restart_cluster, notmaster
  become_user: "{{ cockroach_user }}"


- name: Check status
  shell: "/usr/local/bin/cockroach node status --host {{ inventory_hostname }} --insecure"
  register: status
  when: check_status
  tags: join_cluster,start_cluster,status,restart_cluster
  become_user: "{{ cockroach_user }}"

- name: Check status
  debug: var=status.stdout_lines
  when: check_status
  tags: join_cluster,start_cluster,status, restart_cluster
  become_user: "{{ cockroach_user }}"
