---
# tasks file for cockroach-cluster
- name: Pick Random Cockroach host as master
  add_host:
      name: "{{ item }}"
      groups: cockroach_master
  with_random_choice: "{{ groups[hostgroup] }}"
  delegate_to: localhost
  tags: start_cluster,restart_cluster,stop_cluster

- set_fact:
    cluster_master: "{{ groups['cockroach_master'][0] }}"
  tags: start_cluster,restart_cluster,stop_cluster

- name: Stop cluster
  cockroach_cluster: path={{ install_location }}/{{ install_version }} host={{ inventory_hostname }} state=stopped
  when: stop_cluster
  tags: stop_cluster,restart_cluster

- name: Waiting for port to be released
  wait_for: port={{ cockroach_port }} state=stopped
  when: stop_cluster
  tags: stop_cluster,restart_cluster

- name: Start master node
  cockroach_cluster:
           path={{ install_location }}/{{ install_version }}
           host={{ inventory_hostname }}
           cache={{ cache |default (omit)}}
           log_dir={{ log_dir | default(omit) }}
           locality={{ locality | default(omit) }}
           state=started
  when: inventory_hostname == cluster_master
  tags: start_cluster,restart_cluster

- name: Start other nodes
  cockroach_cluster:
           path={{ install_location }}/{{ install_version }}
           host={{ inventory_hostname }}
           join=True
           cluster_master={{ cluster_master }}
           cache={{ caches |default (omit)}}
           log_dir={{ log_dir | default(omit) }}
           state=started
  when: inventory_hostname != cluster_master
  tags: join_cluster,start_cluster,restart_cluster

- name: Check status
  shell: "{{ install_location }}/{{ install_version }}/cockroach node status --host {{ inventory_hostname }} --insecure"
  register: status
  when: check_status
  tags: join_cluster,start_cluster,status

- name: Check status
  debug: var=status.stdout_lines
  when: check_status
  tags: join_cluster,start_cluster,status
