---
# tasks file for cockroach
- name: Create Cockroach group
  group: name="{{ cockroach_group }}" state=present

- name: Create Cockroach user
  user: name="{{ cockroach_user }}" shell=/bin/bash group="{{ cockroach_group }}" state=present

- name: Create directories
  file: path={{ item }} state=directory owner={{ cockroach_user }} group={{ cockroach_group }} mode=774
  with_items:
       - "{{ install_location_base }}"
       - "{{ certs_dir }}"
       - "{{ ca_dir }}"
       - "{{ log_dir }}"
       - "{{ datastore_basedir }}"
       - "{{ install_stage }}"
       - "{{ datastore }}"
  tags: hostfs

- include: filesystems.yml
  when: configure_host_disks

# - name: remove installation files
#   file: path="{{ install_stage }}/{{ cockroach_binaries.filename }}" state=absent
#   when: remove_install_binaries
#   tags: remove_install_binaries,remove_cluster
#
# - name: Kill all roaches
#   script: kill-all-roaches.sh
#   when: reinstall_cluster or remove_cluster
#   tags: remove_cluster
#   ignore_errors: true

# - name: Remove installation directory
#   file: name={{ install_location }} state=absent
#   when: reinstall_cluster or remove_cluster
#   tags: remove_cluster

- name: remove symlink from /usr/local/bin
  file: src={{ install_location }}/cockroach dest=/usr/local/bin/cockroach state=absent
  when: reinstall_cluster or remove_cluster or remove_symlink
  tags: remove_symlink

- name: Create installation directory
  file: name={{ install_location }} state=directory owner={{ cockroach_user }} group={{ cockroach_group }}
  tags: directories

- name: Get installation files
  get_url: url="{{ binary_url }}/{{ cockroach_binaries.filename }}" dest="{{ install_stage}}/{{ cockroach_binaries.filename }}" validate_certs=false
  when: download_binaries
  tags: download

- name: Unpack/install binaries
  unarchive: src="{{ install_stage}}/{{ cockroach_binaries.filename }}" dest={{ install_location }} extra_opts="--strip-components=1" copy=no owner={{ cockroach_user }} group={{ cockroach_group }}
  tags: install,unpack

- name: create symlink to /usr/local/bin
  file: src={{ install_location }}/cockroach dest=/usr/local/bin/cockroach state=link
  tags: link

- name: test the installation
  shell: "{{ install_location }}/cockroach version"
  register: cversion
  failed_when:
        - not cversion.stdout |search ('v'~install_version )
  tags: test_install

- name: print output
  debug: var=cversion.stdout_lines
  tags: test_install

- name: Add dotprofile
  template: src=dotprofile.j2 dest="/home/{{ cockroach_user}}/.profile_cockroach" backup=true
  tags: install,dotprofile

- name: Make sure profile is loaded
  lineinfile: dest="/home/{{ cockroach_user}}/.bash_profile" line="source /home/{{ cockroach_user}}/.profile_cockroach" state=present backup=yes
  tags: install,dotprofile
