- name: Configure cockroach systemd service
  template: src=cockroachdb.service.j2 dest={{ systemd_config_path }} owner=root mode=644 backup=true
  when: use_systemd
  register: systemd_config
  tags: systemd_config,change_systemd

- name: Register cockroachdb systemd service
  systemd: name={{ systemd_config_service }} daemon_reload=yes enabled=yes
  when: use_systemd and systemd_config.changed
  tags: systemd_config,change_systemd

- name: Stop cluster
  cockroach_cluster: path={{ install_location }} host={{ inventory_hostname }} state=stopped
  when: use_systemd and systemd_config.changed
  tags: stop_cluster_for_systemd,systemd_config
  become_user: "{{ cockroach_user }}"

- pause:
      seconds: 5

- name: Start cockroach node with systemd
  systemd: name={{ systemd_config_service }} state=started
  when: use_systemd and systemd_config.changed
  tags: start_cluster_for_systemd,systemd_config, systemd_start

- name: Check status
  shell: "sleep 5;systemctl status {{ systemd_config_service }}; sleep 5; systemctl status {{ systemd_config_service }}"
  when: use_systemd
  register: status
  tags: start_cluster_for_systemd,systemd_config, systemd_status
  ignore_errors: true

- debug: var=status.stdout_lines
  when: use_systemd
  tags: start_cluster_for_systemd,systemd_config, systemd_status
  ignore_errors: true

- name: Start cockroach node with systemd
  systemd: name={{ systemd_config_service }} state=started
  when: use_systemd
  tags: start_cluster_for_systemd,systemd_config, systemd_start
