---
- name: remove installation files
  file: path="/tmp/{{ cockroach_binaries.filename }}" state=absent
  when: remove_install_binaries
  tags: remove_install_binaries,remove_cluster

- name: Kill all roaches
  script: kill-all-roaches.sh
  when: remove_cluster
  tags: remove_cluster
  ignore_errors: true

- name: remove symlink from /usr/local/bin
  file: src={{ install_location }}/cockroach dest=/usr/local/bin/cockroach state=absent
  when: remove_cluster
  tags: remove_symlink

- name: Remove install/log directories
  file: name={{ item }} state=absent
  with_items:
      - "{{ log_dir }}"
      - "{{ install_location }}"
  when: remove_directories

- name: Remove datastore
  file: name={{ item }} state=absent
  with_items:
      - "{{ store }}"
  when: remove_directories and remove_datastore

- name: Remove Cockroach user
  user: name="{{ cockroach_user }}" state=absent
  when: remove_user
  tags: remove_user

- name: Remove Cockroach group
  group: name="{{ cockroach_group }}" state=absent
  when: remove_user
  tags: remove_user

- name: Remove /home/cockroach
  file: path=/home/cockroach state=absent
  when: remove_user
  tags: remove_user
